name: vinaoptic
description: VinaOptic company

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.3+9

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  simple_animations: ^4.0.2
  material_design_icons_flutter: ^5.0.6595
  get_storage: ^2.1.1
  intl: ^0.17.0
  overlay_support: ^2.0.1
  oktoast: ^3.1.3
  dio: ^4.0.1
  get: ^4.6.5
  logger: ^1.3.0
  flutter_bloc: ^8.1.2
  equatable: ^2.0.5
  carousel_slider: ^4.2.1
  jiffy: ^5.0.0
  persistent_bottom_nav_bar: ^4.0.2
  permission_handler: ^10.0.0
  flutter_animated_dialog: ^2.0.1
  image_picker:
  flutter_barcode_scanner: ^2.0.0
  cached_network_image: ^3.2.1
#  flutter_neat_and_clean_calendar: any
  flutter_datetime_picker: ^1.5.1
  date_time_picker: ^2.1.0
  snapping_sheet: ^3.1.0
  lazy_data_table_plus: ^1.0.0
  simple_gesture_detector: ^0.2.0
  table_calendar:
#  flutter_slidable: ^3.0.0

dev_dependencies:
  flutter_launcher_icons: ^0.9.1
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/icon.png"
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_native_splash:
  color: "#147DCC"
  image: "assets/images/vinaoptic_logo.png"