name: vinaoptic
description: VinaOptic company

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.6+14

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  sqflite: ^2.0.2+1
  percent_indicator: ^3.0.1
  url_launcher: ^6.2.4
  adaptive_dialog: ^1.6.3
  file_picker: ^4.6.1
#  flutter_native_image: ^0.0.6+1
  convert: ^3.0.2

  flutter_math_fork: ^0.6.3+1
  permission_handler: ^9.0.1
  image_picker: ^0.8.5+3
  open_store: ^0.3.1
#
  simple_animations: any
  material_design_icons_flutter: ^5.0.6595
  get_storage: ^2.1.1
  intl: ^0.18.1
  overlay_support: ^2.0.1
  oktoast: ^3.1.3
  dio: ^4.0.1
  get: ^4.6.5
  logger: ^1.3.0
  flutter_bloc: ^8.1.2
  equatable: ^2.0.5
  carousel_slider: ^4.2.1
  jiffy: ^5.0.0
  persistent_bottom_nav_bar: ^4.0.2

  flutter_animated_dialog: ^2.0.1

  flutter_barcode_scanner: ^2.0.0
  cached_network_image: ^3.2.1
#  flutter_neat_and_clean_calendar: any
#  flutter_datetime_picker: ^1.5.1
#  date_time_picker: ^2.1.0
  snapping_sheet: ^3.1.0
  lazy_data_table_plus: ^1.0.0
  simple_gesture_detector: ^0.2.0
  table_calendar:
#  flutter_slidable: ^3.0.0
  omni_datetime_picker: ^1.0.9

dev_dependencies:
  flutter_launcher_icons: ^0.9.1
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/icon.png"

flutter:

  uses-material-design: true

  assets:
    - assets/images/

flutter_native_splash:
  color: "#147DCC"
  image: "assets/images/vinaoptic_logo.png"